### ISSUE TITLE
操作系统win7 64位中文，jdk1.8.0_11，在config-zk-web工程下运行mvn clean install -Dmaven.test.skip报错

### ISSUE THREAD

**Issue by yongk** [dangdangdotcom/config-toolkit#16]
[ERROR] d:\git\config-toolkit\config-zk-web\src\main\java\com\dangdang\config\se
rvice\web\mb\PropertyGroupManagedBean.java:179: 警告: @return 没有说明
[ERROR] * @return
[ERROR] ^
[ERROR] d:\git\config-toolkit\config-zk-web\src\main\java\com\dangdang\config\se
rvice\web\mb\PropertyGroupManagedBean.java:181: 警告: event没有 @param
[ERROR] public void onMenuSelected(SelectEvent event) {
[ERROR] ^
[ERROR] d:\git\config-toolkit\config-zk-web\src\main\java\com\dangdang\config\se
rvice\web\mb\PropertyGroupManagedBean.java:192: 警告: @param 没有说明
[ERROR] * @param event
[ERROR] ^
[ERROR] d:\git\config-toolkit\config-zk-web\src\main\java\com\dangdang\config\se
rvice\web\mb\PropertyGroupManagedBean.java:273: 警告: @param 没有说明
[ERROR] * @param event
[ERROR] ^
[ERROR] d:\git\config-toolkit\config-zk-web\src\main\java\com\dangdang\config\se
rvice\web\mb\PropertyGroupManagedBean.java:303: 警告: @param 没有说明
[ERROR] * @param event
[ERROR] ^

java -version
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

已将换行改成CRLF

note:jdk1.7.0_45没有问题，mvn clean install -Dmaven.test.skip能运行成功。

**Comment by crnlmchina** [comment]
java8对注释要求比较严格，加上-Dmaven.javadoc.skip=true
