### ISSUE TITLE
v2分支监听NodeChildrenChanged事件，并没有处理子节点删除的情况

### ISSUE THREAD

**Issue by afredlyj** [dangdangdotcom/config-toolkit#21]
删除子节点，触发NodeChildrenChanged事件，之后调用`ConfigNode#loadKey`，加载最新的配置，问题在于properties没有清空，无法正确处理子节点被删除的情况。

**Comment by crnlmchina** [comment]
V2FINAL的确有这个问题，V3里面修复了，回头我把V2也打个补丁吧

**Comment by afredlyj** [comment]
升级到v3，客户端也要改？

**Comment by crnlmchina** [comment]
v3的包名有变化，并且添加了xsd的支持，你可以读一下readme和wiki，结构上没有大的变化
升级还是值得的，因为v3添加了不少特性，而且一直在维护
升级的细节问题，可以加到QQ群里寻求帮助，群号：457997852

**Comment by lysongfei** [comment]
现在不是0.0.1-SNAPSHOT版本吗？哪里有V3版本？
