### ISSUE TITLE
spring-boot 1.4.4打包成单个jar文件后，"classpath:application.properties" 无法读取

### ISSUE THREAD

**Issue by shiqingshun** [dangdangdotcom/config-toolkit#22]
把spring-boot项目打成单个jar包，运行时，无法正确读取配置文件

&lt;bean class=&quot;com.dangdang.config.service.file.FileConfigGroup&quot; c:configProfile-ref=&quot;fileConfigProfile&quot; c:location=&quot;classpath:application.properties&quot; /&gt;

sprint-boot版本是1.4.4

**Comment by crnlmchina** [comment]
关于spring boot和config toolkit的整合可以参考一下这个文章：https://github.com/dangdangdotcom/config-toolkit/wiki/spring-boot-integration
