### ISSUE TITLE
关于版本问题

### ISSUE THREAD

**Issue by fish7790714** [dangdangdotcom/config-toolkit#24]
您好 一直在用您们的config toolkit 非常好用，也非常感谢。但是 类似于 guava curator 版本有点略低 是否可以升级下版本 非常感谢

**Comment by crnlmchina** [comment]
您好，感谢您的建议，非常不错
这个问题我考虑过，但是最新版本的guava和curator的API有一些不兼容的变化，升级后可能会迫使用户修改业务代码，并且还有一些其它的类库比如dubbo也使用了curator
基于这个成本问题所以一直没有升级
我再考虑考虑吧，或者您有没有好的方案可以提一下，谢谢！

**Comment by crnlmchina** [comment]
3.3.0版本已升级curator，并且删除了guava依赖

**Comment by fish7790714** [comment]
非常 非常 感谢
