### ISSUE TITLE
建议添加Key和Value的时候自动去除左右的空格（做trim()操作）

### ISSUE THREAD

**Issue by hxy91819** [dangdangdotcom/config-toolkit#31]
很多时候Key和Value都是复制粘贴上去的，总是有粗心的人把末尾的空格粘贴上去。

并且末尾有空格，在配置的页面看不出来。一旦出现问题，比较难定位。

希望能够更新自动trim()的功能，拯救下粗心的程序员。

**Comment by crnlmchina** [comment]
你好，新版的config face已经做了trim，如果不喜欢新版的UI，可以自己稍稍改动一下旧版的config web
